site_name: Meio a Meio
repo_url: https://github.com/mdsreq-fga-unb/2022.1-Meio-a-Meio
site_url: https://mdsreq-fga-unb.github.io/2022.1-Meio-a-Meio/

nav:
- Início: index.md
# - Projeto: ProductVision.md
- Produto:
  - 'Visão': ./produto-projeto/ProductVision.md
  - 'Mvp': ./produto-projeto/MVP.md
  - 'Backlog': ./produto-projeto/Requisitos.md
  - 'Videos cliente' : ./produto-projeto/ClientVideos.md
  - 'Politica de commits': ./produto-projeto/commit_policy.md
  - 'Kanbam': 'https://trello.com/b/lcWQoS87'
  - 'Diagrama de dados Lucidchart': 'https://lucid.app/lucidchart/5f91f189-0a8c-4b74-ad5d-a831a71a1252/edit?viewport_loc=-1562%2C-431%2C3734%2C2154%2C0_0&invitationId=inv_83b530a6-6269-4b7c-a717-5b8ca496e830#'
  - 'Diagramas diversos miro' : 'https://miro.com/app/board/uXjVOlmuidc=/?share_link_id=155231888640'
  - 'Contribuir': 'https://github.com/mdsreq-fga-unb/2022.1-Meio-a-Meio/blob/main/CODE_OF_CONDUCT.md'
  - 'Pbb e Bdd': ./produto-projeto/PBB.md
  - 'USM': ./produto-projeto/US-Mapping.md
  - 'UC diagrama': ./produto-projeto/casos-de-uso.md
  - 'UC professor': ./produto-projeto/US-Professor.md
  - 'US Gestor': ./produto-projeto/US-Gestor.md

- Sprints planing:
  - 'Sprint 01': Sprints/Sprint01/SprintPlanning.md
  - 'Sprint 02': Sprints/Sprint02/SprintPlanning.md
  - 'Sprint 03': Sprints/Sprint03/SprintPlanning.md
  - 'Sprint 04': Sprints/Sprint04/SprintPlanning.md
  - 'Sprint 05': Sprints/Sprint05/SprintPlanning.md
  - 'Sprint 06': Sprints/Sprint06/SprintPlanning.md

- Sprints Review:
  - 'Sprint 01': Sprints/Sprint01/SprintReview.md
  - 'Sprint 02': Sprints/Sprint02/SprintReview.md
  - 'Sprint 03': Sprints/Sprint03/SprintReview.md
  - 'Sprint 04': Sprints/Sprint04/SprintReview.md
  - 'Sprint 05': Sprints/Sprint05/SprintReview.md
  - 'Sprint 06': Sprints/Sprint06/SprintReview.md


theme: 
  name: mkdocs

markdown_extensions:
  # - pymdownx.tasklist
  # - pymdownx.emoji
  # - pymdownx.mark
  # - pymdownx.tilde
